var GAME_LEVELS = [
  ["x          x!x                                                  ",
   "x          x!x                                                  ",
   "xo         x!x                                                  ",
   "xx         x!x                                                  ",
   "x          x!x                                                  ",
   "x          !!!                                                  ",
   "x          !x!                                                  ",
   "x                                                               ",
   "x           p                                                   ",
   "x                                    o                          ",
   "x   xyx                              x                          ",
   "x   xxx                                                         ",
   "xx                                        x                   xx",
   "x                                         x                   x ",
   "x        xxx#xxx                          x                   x ",
   "x        x     x                         xx                   x ",
   "x        x     x                          x                   x ",
   "x        x     x                          x                   x ",
   "x        x     x                          x                  ox ",
   "xyx      x     x                         xx              x  xxx ",
   "xxx @    x     x              xx    x    xx      x          x   ",
   "xxxxxxxxxx     x       xx!!!!!xx         xx               p x   ",
   "               xx!!!!!!xxxxxxxxx!!!!!!!!!xx               h#x   ",
   "               xxxxxxxxx       x!!!!!!!!!xx!!!!!!!!!!!!!!!!!x   ",
   "                               x!!!!!!!!!xx!!!!!!!!!!!!!!!!!x   ",
   "                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                "],

  ["                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                    xx     xx                                 xxxxx      ",
   "                                                                                           x        x    ",
   "                        o                               o                                x x        x    ",
   "                        x                     xxx       o       xxx                    x  #   #       x  ",
   "                                                        o                             x           x      ",
   "    p                         h                                                                 x      x ",
   "  xxxxx                            xx#xx                o                             o      x     x     ",
   " xxxxxxx      xx                                        o                             x     x           x",
   "xxxxxyxxx                                               o                              !!!x         x    ",
   "xxxyxxxxxx                                   x                                  x     !!!                ",
   "yxxxxxyxxx                                              o                       x    !! !!           x   ",
   " xx x xx                                                o                   o   x   !     !            x ",
   "    x                                                   o                   x   x                        ",
   "    x              o   o   o        xxxxxxxxxxxxxxx#xx                          x                        ",
   "    x                                                x                          x                        ",
   "    x        x  x  o   o   o  x   x                  x  o  xxxxxxxxxxxxxxxxxxxxxx                        ",
   "    x        x  x             x   x                  x  h  x                                             ",
   "    x  @     x  x             x!!!x                  x!!!!!x                                             ",
   "xxxxx#xxxxiiix  xxxxxxxxxxxxxxx!!!x            o     x!!!!!x                                             ",
   "                              xxxxxx                 xxxxxxx                                             ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                              xyx                                                        ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                     xyx                                                                 ",
   "             xxxx                                                                                        ",
   "             x                                                                                           ",
   "             x              xyx                                                                          ",
   "      xyx    x                                                                                           ",
   "             x                                                                                           ",
   "o            x     xyx                                                                                   ",
   "xy!!!!!!!!!!!x                                                                                           ",
   "xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

  ["                                                              x                                                         ",
   "                                                              x                                                         ",
   "                                                              x                                                         ",
   "                                                              x                                                         ",
   "                                                              x                                                         ",
   "                                                              x                                                         ",
   "                                                              x                                                         ",
   "                                                              x                      x                                 o",
   "                                                     xxxxxxxx x                                                       xx",
   "                                                     x        x                              o                 o        ",
   "                                                     x        x              #              xyx                x        ",
   "                                                     x  xxxxxxx                             xxx                         ",
   "                                                    xx xx                                               x               ",
   "                                                     x  x                                                               ",
   "                                                     x  xo x                                                            ",
   "                                                     xx xx x                                                            ",
   "                                                    xx  x  x                p     p     p     p    o                    ",
   "                                                     x  x  x              hhhhh hhhhh hhhhh hhhhh xyx                   ",
   "                                                     x xx  x                                      xxx                   ",
   "       @                  o                 o        x     x                                                            ",
   "xxxxxxxxx        x        x        x        x       xx     x                                                            ",
   "                                                     x xxx x                                                            ",
   "                                                     x!xxxyx                                                            ",
   "                                                     xxxxxxx                                             o              ",
   "                                                                                                        xyx             ",
   "                                                           x                                            xxx             ",
   "                                                           x                                                            ",
   "         xyx                                               x                                                            ",
   "         xxx       xiiiix   xiiiix   xiiiix                x                                                            ",
   "                                                           x                                                            ",
   "                                                                                                                        ",
   "                                                            xxxxx     x#x     h     x#x      h       xyx                ",
   "                                                                                                                        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

   [" x   x                           ",
    "  x x                     # x    ",
    "   x  xxx x x   x       x   xxxx ",
    "   x  x x x x    x  x  x  x x  x ",
    "   x  xxx xxx     xxxxx   x x  x ",
    "                                 ",
    "                @                ",
    "!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
